CREATE TABLE participants (
 id INTEGER PRIMARY KEY AUTOINCREMENT,
 name TEXT NOT NULL,
 phone_number TEXT NOT NULL,
 date_of_study DATETIME NOT NULL,
 intro_text TEXT DEFAULT "",
 rem1 TEXT DEFAULT "",
 rem2 TEXT DEFAULT "",
 rem3 TEXT DEFAULT "",
 rem4 TEXT DEFAULT "",
 pay1 TEXT DEFAULT "",
 rem5 TEXT DEFAULT "",
 rem6 TEXT DEFAULT "",
 pay2 TEXT DEFAULT "",
 rem7 TEXT DEFAULT "",
 rem8 TEXT DEFAULT "",
 pay3 TEXT DEFAULT "",
 ignore TEXT DEFAULT "False"
)